name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        go: ["1.21", "1.20"]
        platform: [ubuntu-latest] # can not run in windows OS
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: go mod package cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('tests/go.mod') }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: |
          go test ./... -race

      - name: govulncheck 
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: 1.21.8

      - name: Coverage
        run: |
          make coverage-diff


